apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "chart.fullname" . }}-mongo
spec:
  podSelector:
    matchLabels:
      app: mongodb
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "chart.name" . }}
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}