apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "chart.fullname" . }}-api
spec:
  podSelector:
    matchLabels:
      app: {{ template "chart.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  {{- if .Values.rest.enabled }}
  - from:
    - namespaceSelector:
        matchLabels:
          "kube-mail.helmich.me/api-access": "true"
    ports:
    - protocol: TCP
      port: {{ .Values.rest.service.internalPort }}
  {{- end }}
  {{- if .Values.grpc.enabled }}
  - from:
    - namespaceSelector:
        matchLabels:
          "kube-mail.helmich.me/api-access": "true"
    ports:
    - protocol: TCP
      port: {{ .Values.grpc.service.internalPort }}
  {{- end }}
  - from:
    - namespaceSelector:
        matchLabels:
          "kube-mail.helmich.me/smtp-access": "true"
    ports:
    - protocol: TCP
      port: {{ .Values.smtp.service.internalPort }}