apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.rest.enabled }}
    - port: {{ .Values.rest.service.externalPort }}
      targetPort: {{ .Values.rest.service.internalPort }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.grpc.enabled }}
    - port: {{ .Values.grpc.service.externalPort }}
      targetPort: {{ .Values.grpc.service.internalPort }}
      protocol: TCP
      name: grpc
    {{- end }}
    - port: {{ .Values.smtp.service.externalPort }}
      targetPort: {{ .Values.smtp.service.internalPort }}
      protocol: TCP
      name: smtp
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
